force-app/main/default/objects/AccessNow_SObject_to_Request_Mapping__c/AccessNow_SObject_to_Request_Mapping__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Access Now SObject to Request Mapping</label>
</CustomObject>

force-app/main/default/objects/AccessNow_SObject_to_Request_Mapping__c/fields/AccessNow_Request_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>AccessNow_Request_Field_API_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>AccessNow Request Field API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccessNow_SObject_to_Request_Mapping__c/fields/SObject_API_Name__c.field-meta.xml
<CustomField>
    <fullName>SObject_API_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>SObject API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccessNow_SObject_to_Request_Mapping__c/fields/SObject_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>SObject_Field_API_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>SObject Field API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ACNW_Request__c/ACNW_Request__c.object-meta.xml
<CustomObject>
    <label>Request</label>
    <nameField>
        <displayFormat>R-{0000000}</displayFormat>
        <label>Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AccessNowSObjToRequestCreationTest.cls
@istest
private class AccessNowSObjToRequestCreationTest {
    private static testmethod void test() {
        insert new AccessNow_SObject_to_Request_Mapping__c(Name = 'test1', SObject_API_Name__c = 'account', SObject_Field_API_Name__c = 'name', AccessNow_Request_Field_API_Name__c = 'accessnow__Reference_Number__c');

        Account a = new Account(Name = 'test');
        insert a;

        list<id> rids = AccessNowSObjToRequestCreation.createRequest(new list<id> { a.Id });
        ACNW_Request__c ra = [select accessnow__Reference_Number__c from ACNW_Request__c where Id in :rids];
        System.assert(ra.accessnow__Reference_Number__c == a.Name, 'Reference number should have been ' + a.Name + ' but got '  + ra.accessnow__Reference_Number__c);
    }
}