force-app/main/default/objects/ACNW_Data_Audit_Log__c/ACNW_Data_Audit_Log__c.object-meta.xml
<CustomObject>
    <label>Data Audit Log</label>
    <nameField>
        <displayFormat>DAL-{000000000}</displayFormat>
        <label>Data Audit Log Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Audit Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ACNW_Data_Audit_Log__c/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ACNW_Data_Audit_Log__c/fields/Logged_In_As__c.field-meta.xml
<CustomField>
    <fullName>Logged_In_As__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Logged In As</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Data_Audit_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ACNW_Data_Audit_Log__c/fields/New_Value__c.field-meta.xml
<CustomField>
    <fullName>New_Value__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>New Value</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ACNW_Data_Audit_Log__c/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Object Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ACNW_Data_Audit_Log__c/fields/Old_Value__c.field-meta.xml
<CustomField>
    <fullName>Old_Value__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Old Value</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ACNW_Data_Audit_Log__c/fields/Parent_Id__c.field-meta.xml
<CustomField>
    <fullName>Parent_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Parent Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ACNW_Data_Audit_Log__c/fields/Parent_Name__c.field-meta.xml
<CustomField>
    <fullName>Parent_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Record Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ACNW_Data_Audit_Log__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <label>Request</label>
    <referenceTo>ACNW_Request__c</referenceTo>
    <relationshipLabel>Data Audit Logs</relationshipLabel>
    <relationshipName>Data_Audit_Logs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ACNW_Request__c/ACNW_Request__c.object-meta.xml
<CustomObject>
    <label>Request</label>
    <nameField>
        <displayFormat>R-{0000000}</displayFormat>
        <label>Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ACNW_Request__c/fields/Actual_End_Time__c.field-meta.xml
<CustomField>
    <fullName>Actual_End_Time__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Actual End Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ACNW_Request__c/fields/Actual_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Actual_Start_Time__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Actual Start Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ACNW_Request__c/fields/Manually_Revoked__c.field-meta.xml
<CustomField>
    <fullName>Manually_Revoked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Manually Revoked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ACNW_Request__c/fields/Requested_End_Time__c.field-meta.xml
<CustomField>
    <fullName>Requested_End_Time__c</fullName>
    <formula>Requested_Start_Time__c + value(text(Duration_Hours__c)) / 24</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Requested End Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ACNW_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AuditFuncs.cls
global with sharing class AuditFuncs {
    // called from process builder + time based
    @InvocableMethod
    public static void auditRecentlyViewed(List<Id> requestIds) {
        // this can ONLY be done in the context of the logged in user since RecentlyViewed is only available for the logged in user
        DateTime dt = System.now();
        List<ACNW_Request__c> reqs = new List<ACNW_Request__c>();
        for (ACNW_Request__c r : [select Id, Actual_Start_Time__c, Actual_End_Time__c, Status__c, OwnerId, Requested_End_Time__c, Manually_Revoked__c, (select Id from Data_Audit_Logs__r where Field__c = 'viewed' limit 1) from ACNW_Request__c where Actual_Start_Time__c <> null and Actual_Start_Time__c < :dt and Id in :requestIds]) {
            if (r.Data_Audit_Logs__r.isEmpty() && ((r.Actual_End_Time__c == null && SiteSwitcherFuncs.needToStop(r)) || (r.Actual_End_Time__c != null && r.Actual_End_Time__c <= dt))) {
            	reqs.add(r);
            }
        }

        Id uid = null;
        DateTime minDate = null;

        for (ACNW_Request__c req : reqs) {
            if (uid != null && uid != req.OwnerId) throw new AuditFuncsException('Received multiple owner ids in audit request');
            uid = req.OwnerId;
            if (minDate == null || minDate > req.Actual_Start_Time__c) minDate = req.Actual_Start_Time__c;
        }

        if (reqs.isEmpty() || UserInfo.getUserId() != uid) return;

        List<ACNW_Data_Audit_Log__c> toInsert = new List<ACNW_Data_Audit_Log__c>();
        for (RecentlyViewed rv : [select Id, Type, LastViewedDate, Name from RecentlyViewed where LastViewedDate >= :minDate]) {
            for (ACNW_Request__c req : reqs) {
                if (rv.LastViewedDate >= req.Actual_Start_Time__c && rv.LastViewedDate <= (req.Actual_End_Time__c == null ? dt : req.Actual_End_Time__c)) {
                    toInsert.add(new ACNW_Data_Audit_Log__c(
                        Logged_In_As__c = uid,
                        Parent_Id__c = rv.Id,
                        Field__c = 'viewed',
                        Date__c = rv.LastViewedDate,
                        Object_Name__c = rv.Type,
                        Parent_Name__c = rv.Name,
                        Request__c = req.Id
                    ));
                }
            }
        }

        if (!toInsert.isEmpty()) insert toInsert;
    }

    // called from real-time triggers deployed in the org
    global static void auditRecords() {
        // if impersonating, we get these afterwards via the history trigger
        Id userId = UserInfo.getUserId();

        Id requestId = null;

        for (ACNW_Request__c req : [select Id from ACNW_Request__c where Status__c = 'In Progress' and OwnerId = :userinfo.getUserId()]) {
            requestId = req.Id;
        }

        if (requestId == null) return;

        list<sobject> recs = trigger.isDelete ? trigger.old : trigger.new;
        map<id, sobject> oldRecs = trigger.isUpdate ? trigger.oldMap : null;

        Schema.DescribeSObjectResult describeRes = recs[0].getsobjecttype().getdescribe();
        String objectName = describeRes.getName();

        Map<String, Schema.SObjectField> fields = describeRes.fields.getMap();

        String nameField = null;
        if (fields.containsKey('name')) {
            nameField = 'Name';
        } else {
            for (Schema.SObjectField fld : fields.values()) {
                if (fld.getDescribe().isNameField()) {
                    nameField = fld.getDescribe().getName();
                }
            }
        }

        list<ACNW_Data_Audit_Log__c> toInsert = new list<ACNW_Data_Audit_Log__c>();

        for (sobject r : recs) {
            String recordName = nameField == null ? null : (String)r.get(nameField);

            if (trigger.isInsert) {
                toInsert.add(new ACNW_Data_Audit_Log__c(
                    Logged_In_As__c = UserInfo.getUserId(),
                    Parent_Id__c = r.Id,
                    Field__c = 'created',
                    Date__c = System.now(),
                    Object_Name__c = objectName,
                    Parent_Name__c = recordName,
                    Request__c = requestId
                ));
            } else if (trigger.isUpdate) {
                SObject oldRec = oldRecs.get(r.Id);
                for (String f : fields.keySet()) {
                    if (f == 'lastmodifieddate' || f == 'lastmodifiedbyid' || f == 'systemmodstamp') continue;

                    if (oldRec.get(f) != r.get(f)) {
                        toInsert.add(new ACNW_Data_Audit_Log__c(
                            Logged_In_As__c = UserInfo.getUserId(),
                            Parent_Id__c = r.Id,
                            Field__c = fields.get(f).getDescribe().getName(),
                            Old_Value__c = oldRec.get(f) == null ? '' : '' + oldRec.get(f),
                            New_Value__c = r.get(f) == null ? '' : '' + r.get(f),
                            Date__c = System.now(),
                            Object_Name__c = objectName,
                            Parent_Name__c = recordName,
                            Request__c = requestId
                        ));
                    }
                }
            } else if (trigger.isDelete) {
                toInsert.add(new ACNW_Data_Audit_Log__c(
                    Logged_In_As__c = UserInfo.getUserId(),
                    Parent_Id__c = r.Id,
                    Field__c = 'deleted',
                    Date__c = System.now(),
                    Object_Name__c = objectName,
                    Parent_Name__c = recordName,
                    Request__c = requestId
                ));
            } else if (trigger.isUndelete) {
                toInsert.add(new ACNW_Data_Audit_Log__c(
                    Logged_In_As__c = UserInfo.getUserId(),
                    Parent_Id__c = r.Id,
                    Field__c = 'undeleted',
                    Date__c = System.now(),
                    Object_Name__c = objectName,
                    Parent_Name__c = recordName,
                    Request__c = requestId
                ));
            }
        }

        if (!toInsert.isEmpty()) insert toInsert;
    }
    class AuditFuncsException extends Exception { }
}