force-app/main/default/objects/ACNW_Data_Audit_Log__c/ACNW_Data_Audit_Log__c.object-meta.xml
<CustomObject>
    <label>Data Audit Log</label>
    <nameField>
        <displayFormat>DAL-{000000000}</displayFormat>
        <label>Data Audit Log Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Audit Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ACNW_Data_Audit_Log__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <label>Request</label>
    <referenceTo>ACNW_Request__c</referenceTo>
    <relationshipLabel>Data Audit Logs</relationshipLabel>
    <relationshipName>Data_Audit_Logs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ACNW_Permission__c/ACNW_Permission__c.object-meta.xml
<CustomObject>
    <label>Permission</label>
    <nameField>
        <displayFormat>P-{0000000}</displayFormat>
        <label>Permission Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Permissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ACNW_Permission__c/fields/License_Required__c.field-meta.xml
<CustomField>
    <fullName>License_Required__c</fullName>
    <label>License Required</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>Salesforce Platform</fullName>
            </value>
            <value>
                <fullName>Service Cloud</fullName>
            </value>
            <value>
                <fullName>Chatter Only User</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ACNW_Permission__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Name</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ACNW_Permission__c/fields/SF_Permission_Id__c.field-meta.xml
<CustomField>
    <fullName>SF_Permission_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>SF Permission Id</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ACNW_Permission__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Permission Bundles</fullName>
            </value>
            <value>
                <fullName>Permission Set</fullName>
            </value>
            <value>
                <fullName>Permission Set Group</fullName>
            </value>
            <value>
                <fullName>Profile</fullName>
            </value>
            <value>
                <fullName>Role</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ACNW_Request__c/ACNW_Request__c.object-meta.xml
<CustomObject>
    <label>Request</label>
    <nameField>
        <displayFormat>R-{0000000}</displayFormat>
        <label>Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ACNW_Request__c/fields/Provision_Immediately__c.field-meta.xml
<CustomField>
    <fullName>Provision_Immediately__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Provision Immediately</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ACNW_Request__c/fields/Reference_Number__c.field-meta.xml
<CustomField>
    <fullName>Reference_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Reference Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ACNW_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ACNW_Request_Permission__c/ACNW_Request_Permission__c.object-meta.xml
<CustomObject>
    <label>Request Permission</label>
    <nameField>
        <displayFormat>RP-{0000000}</displayFormat>
        <label>Request Permission Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Request Permissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ACNW_Request_Permission__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <label>Request</label>
    <referenceTo>ACNW_Request__c</referenceTo>
    <relationshipLabel>Request Permissions</relationshipLabel>
    <relationshipName>Request_Permissions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ACNW_Request_Permission__c/fields/User_Permission__c.field-meta.xml
<CustomField>
    <fullName>User_Permission__c</fullName>
    <label>User Permission</label>
    <referenceTo>ACNW_User_Permission__c</referenceTo>
    <relationshipLabel>Request Permissions</relationshipLabel>
    <relationshipName>Request_Permissions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ACNW_User_Permission__c/ACNW_User_Permission__c.object-meta.xml
<CustomObject>
    <label>User Permission</label>
    <nameField>
        <displayFormat>UP-{0000000}</displayFormat>
        <label>User Permission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Permissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ACNW_User_Permission__c/fields/Permission__c.field-meta.xml
<CustomField>
    <fullName>Permission__c</fullName>
    <label>Permission</label>
    <referenceTo>ACNW_Permission__c</referenceTo>
    <relationshipLabel>User Permissions</relationshipLabel>
    <relationshipName>User_Permissions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ACNW_User_Permission__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User_Permissions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RequestTest.cls
@istest
private class RequestTest {
    private static testmethod void testSwitch() {
        EncryptionUtils.setupEncryption();

        ACNW_Request__c r = new ACNW_Request__c(Provision_Immediately__c = true, Reference_Number__c = 'test');
        insert r;

        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();

        RestContext.request = req;
        RestContext.response = res;

        SiteSwitcher.switch();

        req.params.put('cs', EncryptionUtils.encryptData(r.Id));
        SiteSwitcher.switch();

        req.params.put('id', UserInfo.getUserId());
        SiteSwitcher.switch();

        req.params.put('id', r.Id);
        SiteSwitcher.switch();

        SiteSwitcher.addRemovePermissions(r.id);
        r.Status__c = 'In Progress';
        update r;
        try {
            SiteSwitcher.addRemovePermissions(r.id);
        } catch(Exception ex) {
        }

        r.Status__c = 'Completed';
        update r;
        try {
            SiteSwitcher.addRemovePermissions(r.id);
        } catch(Exception ex) {
        }

        try {
            SiteSwitcher.addRemovePermissions(null);
        } catch(Exception ex) {
        }
        try {
            SiteSwitcher.switch(null);
        } catch(Exception ex) {
        }

        System.assert(true);
    }
    private static testmethod void test() {
        EncryptionUtils.setupEncryption();

        ACNW_Permission__c perm = new ACNW_Permission__c(Name__c = 'testing', SF_Permission_Id__c = [select Id from PermissionSet where IsOwnedByProfile = false limit 1].Id, License_Required__c = 'Salesforce', Type__c = 'Permission Set');
        insert perm;

        ACNW_User_Permission__c up = new ACNW_User_Permission__c(Permission__c = perm.Id, User__c = UserInfo.getUserId());
        insert up;

        ACNW_Request__c req = new ACNW_Request__c(Provision_Immediately__c = true, Reference_Number__c = 'test');
        insert req;

        ACNW_Request_Permission__c rp = new ACNW_Request_Permission__c(Request__c = req.Id, User_Permission__c = up.Id);
        insert rp;

        req.Status__c = 'Pending Approval';
        update req;

        SiteSwitcherFuncs.callSiteSwitchFlow(new List<Id> { req.Id });
        try {
            Integer i = 1/0;
        } catch(Exception ex) {
            SiteSwitcherFuncs.setError(req.Id, ex);
        }

        System.assert(true);
    }
    private static testmethod void test2() {
        EncryptionUtils.setupEncryption();

        ACNW_Permission__c perm = new ACNW_Permission__c(Name__c = 'testing', SF_Permission_Id__c = [select Id from Profile limit 1].Id, License_Required__c = 'Salesforce', Type__c = 'Profile');
        insert perm;

        ACNW_User_Permission__c up = new ACNW_User_Permission__c(Permission__c = perm.Id, User__c = UserInfo.getUserId());
        insert up;

        ACNW_Request__c req = new ACNW_Request__c(Provision_Immediately__c = true, Reference_Number__c = 'test');
        insert req;

        ACNW_Request_Permission__c rp = new ACNW_Request_Permission__c(Request__c = req.Id, User_Permission__c = up.Id);
        insert rp;

        req.Status__c = 'Pending Approval';
        update req;

        SiteSwitcherFuncs.callSiteSwitchFlow(new List<Id> { req.Id });

        System.assert(true);
    }
    private static testmethod void test3() {
        PostInstallClass postinstall = new PostInstallClass();
        Test.testInstall(postinstall, null);
        System.assert(true);
    }
    private static testmethod void test4() {
        SiteSwitcherFuncs.hasRequestAlreadyInProgress(null, null);
        try {
        	SiteSwitcherFuncs.setError(new Set<Id>(), null);
        } catch(Exception ex) {}
        new SiteSwitcherfuncs.ImpersonationTime(null, null, null);
        SiteSwitcherFuncs.getImpersonationTimes(new ACNW_Request__c());
        System.assert(true);
    }
    private static testmethod void test5() {
        SiteSwitcher.handleImpersonationsForHistoryObject(new ACNW_Request__c(), 'AccountHistory', new list<SiteSwitcherFuncs.ImpersonationTime> { new SiteSwitcherFuncs.ImpersonationTime(System.now(), System.now(), UserInfo.getUserId()) }, new list<ACNW_Data_Audit_Log__c>());
        SiteSwitcher.handleImpersonationsForObject(new ACNW_Request__c(), 'Account', new list<SiteSwitcherFuncs.ImpersonationTime> { new SiteSwitcherFuncs.ImpersonationTime(System.now(), System.now(), UserInfo.getUserId()) }, new list<ACNW_Data_Audit_Log__c>());
        SiteSwitcher.getPermissionSetsForGroup(new Set<Id>());
        SiteSwitcherFuncs.getPermsForAccessNowPermissionGroup(new Set<Id>());
    }
}