force-app/main/default/objects/ACNW_Permission__c/ACNW_Permission__c.object-meta.xml
<CustomObject>
    <label>Permission</label>
    <nameField>
        <displayFormat>P-{0000000}</displayFormat>
        <label>Permission Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Permissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ACNW_Permission__c/fields/License_Required__c.field-meta.xml
<CustomField>
    <fullName>License_Required__c</fullName>
    <label>License Required</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>Salesforce Platform</fullName>
            </value>
            <value>
                <fullName>Service Cloud</fullName>
            </value>
            <value>
                <fullName>Chatter Only User</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ACNW_Permission__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Name</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ACNW_Permission__c/fields/SF_Permission_Id__c.field-meta.xml
<CustomField>
    <fullName>SF_Permission_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>SF Permission Id</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ACNW_Permission__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Permission Bundles</fullName>
            </value>
            <value>
                <fullName>Permission Set</fullName>
            </value>
            <value>
                <fullName>Permission Set Group</fullName>
            </value>
            <value>
                <fullName>Profile</fullName>
            </value>
            <value>
                <fullName>Role</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ACNW_Request__c/ACNW_Request__c.object-meta.xml
<CustomObject>
    <label>Request</label>
    <nameField>
        <displayFormat>R-{0000000}</displayFormat>
        <label>Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ACNW_Request__c/fields/Duration_Hours__c.field-meta.xml
<CustomField>
    <fullName>Duration_Hours__c</fullName>
    <label>Duration (Hours)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>.05</fullName>
                <default>true</default>
                <label>.05</label>
            </value>
            <value>
                <fullName>0.1</fullName>
            </value>
            <value>
                <fullName>0.5</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ACNW_Request__c/fields/Last_Error__c.field-meta.xml
<CustomField>
    <fullName>Last_Error__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Last Error</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ACNW_Request__c/fields/Manually_Revoked__c.field-meta.xml
<CustomField>
    <fullName>Manually_Revoked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Manually Revoked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ACNW_Request__c/fields/Provision_Immediately__c.field-meta.xml
<CustomField>
    <fullName>Provision_Immediately__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Provision Immediately</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ACNW_Request__c/fields/Reference_Number__c.field-meta.xml
<CustomField>
    <fullName>Reference_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Reference Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ACNW_Request__c/fields/Requested_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Requested_Start_Time__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Requested Start Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ACNW_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ACNW_Request_Permission__c/ACNW_Request_Permission__c.object-meta.xml
<CustomObject>
    <label>Request Permission</label>
    <nameField>
        <displayFormat>RP-{0000000}</displayFormat>
        <label>Request Permission Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Request Permissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ACNW_Request_Permission__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <label>Request</label>
    <referenceTo>ACNW_Request__c</referenceTo>
    <relationshipLabel>Request Permissions</relationshipLabel>
    <relationshipName>Request_Permissions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ACNW_Request_Permission__c/fields/User_Permission__c.field-meta.xml
<CustomField>
    <fullName>User_Permission__c</fullName>
    <label>User Permission</label>
    <referenceTo>ACNW_User_Permission__c</referenceTo>
    <relationshipLabel>Request Permissions</relationshipLabel>
    <relationshipName>Request_Permissions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ACNW_Setup_Audit_Log__c/ACNW_Setup_Audit_Log__c.object-meta.xml
<CustomObject>
    <label>Setup Audit Log</label>
    <nameField>
        <displayFormat>SAL-{000000000}</displayFormat>
        <label>Setup Audit Log Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Setup Audit Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ACNW_Setup_Audit_Log__c/fields/Activity__c.field-meta.xml
<CustomField>
    <fullName>Activity__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Activity</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ACNW_Setup_Audit_Log__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ACNW_Setup_Audit_Log__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <label>Request</label>
    <referenceTo>ACNW_Request__c</referenceTo>
    <relationshipName>Audit_Logs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ACNW_Setup_Audit_Log__c/fields/Section__c.field-meta.xml
<CustomField>
    <fullName>Section__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Section</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ACNW_User_Permission__c/ACNW_User_Permission__c.object-meta.xml
<CustomObject>
    <label>User Permission</label>
    <nameField>
        <displayFormat>UP-{0000000}</displayFormat>
        <label>User Permission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Permissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ACNW_User_Permission__c/fields/Permission__c.field-meta.xml
<CustomField>
    <fullName>Permission__c</fullName>
    <label>Permission</label>
    <referenceTo>ACNW_Permission__c</referenceTo>
    <relationshipLabel>User Permissions</relationshipLabel>
    <relationshipName>User_Permissions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ACNW_User_Permission__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User_Permissions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AccessNowRequestControllerTest.cls
@istest
private class AccessNowRequestControllerTest {
    private static testmethod void test() {
        EncryptionUtils.setupEncryption();
        try {
            insert new ACNW_Permission__c(Name__c = 'Testing', SF_Permission_Id__c = 'sadf', License_Required__c = 'Salesforce', Type__c = 'Permission Set');
        } catch(Exception ex) {
        }

        try {
            insert new ACNW_Permission__c(Name__c = 'Testing', SF_Permission_Id__c = UserInfo.getUserId(), License_Required__c = 'Salesforce', Type__c = 'Permission Set');
        } catch(Exception ex) {
        }

        try {
            insert new ACNW_Permission__c(Name__c = 'Testing', SF_Permission_Id__c = 'sadf', License_Required__c = 'Salesforce', Type__c = 'Permission Set Group');
        } catch(Exception ex) {
        }

        try {
            insert new ACNW_Permission__c(Name__c = 'Testing', SF_Permission_Id__c = UserInfo.getUserId(), License_Required__c = 'Salesforce', Type__c = 'Permission Set Group');
        } catch(Exception ex) {
        }

        try {
            insert new ACNW_Permission__c(Name__c = 'Testing', SF_Permission_Id__c = UserInfo.getUserId(), License_Required__c = 'Salesforce', Type__c = 'Profile');
        } catch(Exception ex) {
        }

        try {
            insert new ACNW_Permission__c(Name__c = 'Testing', SF_Permission_Id__c = UserInfo.getUserId(), License_Required__c = 'Salesforce', Type__c = '?');
        } catch(Exception ex) {
        }
    }
    private static testmethod void test2() {
        ACNW_Permission__c perm = new ACNW_Permission__c(Name__c = 'Testing', SF_Permission_Id__c = [select Id from PermissionSet where IsOwnedByProfile = false limit 1].Id, License_Required__c = 'Salesforce', Type__c = 'Permission Set');
        insert perm;

        ACNW_Permission__c perm2 = new ACNW_Permission__c(Name__c = 'Testing', SF_Permission_Id__c = [select Id from Profile limit 1].Id, License_Required__c = 'Salesforce', Type__c = 'Profile');
        insert perm2;

        //ACNW_Permission__c perm3 = new ACNW_Permission__c(Name__c = 'Testing', SF_Permission_Id__c = [select Id from PermissionSetGroup limit 1].Id, License_Required__c = 'Salesforce', Type__c = 'Permission Set Group');
        //insert perm3;

        ACNW_User_Permission__c up = new ACNW_User_Permission__c(Permission__c = perm.Id, User__c = UserInfo.getUserId());
        insert up;

        ACNW_User_Permission__c up2 = new ACNW_User_Permission__c(Permission__c = perm2.Id, User__c = UserInfo.getUserId());
        insert up2;

        // test cancellation
        ACNW_Request__c r = new ACNW_Request__c();
        ApexPages.StandardController std = new ApexPages.StandardController(r);
        AccessNowRequestController cr = new AccessNowRequestController(std);
        cr.req.Provision_Immediately__c = false;
        cr.req.Reference_Number__c = 'hello';
        cr.perms[0].checked = true;
        cr.req.Provision_Immediately__c = true;

        Object obj = cr.allowCancel;
        obj = cr.setupAuditLog;

        cr.save();
        cr.cancel();


        // test save and provision
        r = new ACNW_Request__c();
        std = new ApexPages.StandardController(r);
        cr = new AccessNowRequestController(std);
        cr.req.Provision_Immediately__c = false;
        cr.req.Reference_Number__c = 'hello';

        obj = cr.allowRetry;

        try {
            cr.save();
        } catch(Exception ex) {
        }
        cr.req.Last_Error__c = 'test';
        cr.perms[0].checked = true;
        try {
            cr.save();
        } catch(Exception ex) {
        }

        cr.req.Requested_Start_Time__c = System.today() + 10;
        try {
            cr.save();
        } catch(Exception ex) {
        }

        cr.req.Requested_Start_Time__c = null;
        cr.req.Provision_Immediately__c = true;
        try {
            cr.save();
        } catch(Exception ex) {
        }
        cr.submitForApproval();
    }
    private static testmethod void test3() {
        ACNW_Permission__c perm = new ACNW_Permission__c(Name__c = 'Testing', SF_Permission_Id__c = [select Id from PermissionSet where IsOwnedByProfile = false limit 1].Id, License_Required__c = 'Salesforce', Type__c = 'Permission Set');
        insert perm;

        ACNW_Permission__c perm2 = new ACNW_Permission__c(Name__c = 'Testing', SF_Permission_Id__c = [select Id from Profile limit 1].Id, License_Required__c = 'Salesforce', Type__c = 'Profile');
        insert perm2;

        //ACNW_Permission__c perm3 = new ACNW_Permission__c(Name__c = 'Testing', SF_Permission_Id__c = [select Id from PermissionSetGroup limit 1].Id, License_Required__c = 'Salesforce', Type__c = 'Permission Set Group');
        //insert perm3;

        ACNW_User_Permission__c up = new ACNW_User_Permission__c(Permission__c = perm.Id, User__c = UserInfo.getUserId());
        insert up;

        ACNW_User_Permission__c up2 = new ACNW_User_Permission__c(Permission__c = perm2.Id, User__c = UserInfo.getUserId());
        insert up2;

        ACNW_Request__c r = new ACNW_Request__c();
        ApexPages.StandardController std = new ApexPages.StandardController(r);
        AccessNowRequestController cr = new AccessNowRequestController(std);
        cr.req.Provision_Immediately__c = false;
        cr.req.Reference_Number__c = 'hello';

        cr.perms[0].checked = true;
        cr.req.Requested_Start_Time__c = null;
        cr.req.Provision_Immediately__c = true;
        cr.save();

        r = cr.req;

        cr.submitForApproval();
        r = [select Id, Status__c from ACNW_Request__c where Id = :r.Id];

        Test.startTest();

        insert new ACNW_Setup_Audit_Log__c(Activity__c = 'a', Section__c = 'a', Date__c = System.now(), Request__c = r.Id);

        System.assert(r.Status__c == 'Approved', 'Expecting Approved, got ' + r.Status__c); // should auto approve

        String switchResult = SiteSwitcher.switch(r.Id);
        System.assert(switchResult == 'OK', switchResult);

        r = [select Id, Status__c from ACNW_Request__c where Id = :r.Id];
        //System.assert(r.Status__c == 'In Progress', 'Expecting In Progress, got ' + r.Status__c);

        try {
            delete [select Id from ACNW_Request_Permission__c where Request__c = :r.Id];
        } catch(Exception ex) {
        }

        try {
            //delete [select Id from ACNW_Request__c where Id = :r.Id];
        } catch(Exception ex) {
        }

        //User_Permission__c up2 = new User_Permission__c(Permission__c = perm.Id, User__c = UserInfo.getUserId());
        //insert up2;

        try {
            ACNW_Request_Permission__c rp = [select Id from ACNW_Request_Permission__c where Request__c = :r.Id];
            rp.User_Permission__c = up.Id;
            update rp;
        } catch(Exception ex) {
        }

        std = new ApexPages.StandardController(r);
        cr = new AccessNowRequestController(std);
        cr.req = new ACNW_Request__c();

        ApexPages.currentPage().getParameters().put('idd', UserInfo.getUserID());
        cr.reloadUserPermsFunc();

        try {
            cr.req.Duration_Hours__c = '6';
            cr.save();
        } catch(Exception ex) {
        }

        try {
            cr.submitForApproval();
        } catch(Exception ex) {
        }

        std = new ApexPages.StandardController(r);
        cr = new AccessNowRequestController(std); 
        cr.req = new ACNW_Request__c();

        try {
            cr.revoke();
        } catch(Exception ex) {
        }

        try {
            cr.retry();
        } catch(Exception ex) {
        }

        try {
        	switchResult = SiteSwitcher.switch(r.Id);
        } catch(Exception ex) {
        }

        //System.assert(switchResult == 'OK', switchResult);

        try {        
        	r = [select Id, Manually_Revoked__c from ACNW_Request__c where Id = :r.Id];
        } catch(Exception ex) {
        }

        //System.assert(r.Manually_Revoked__c == true);

        try {
            r.Manually_Revoked__c = false;
            update r;
            r.Manually_Revoked__c = true;
            update r;
        } catch(Exception ex) {
        }
    }
}